### PR TITLE
fix: change encrypt/decrpyt method to AES256 cryptography

### LINKED ISSUE #52: bug: incorrect "OraclePrivKey" encrypt
We use the encryption and decryption method provided by btcec.

**crypto/encrypt.go**
```go


// Encrypt encrypts data using a secp256k1 public key (ECIES)
func Encrypt(pubKey *btcec.PublicKey, data []byte) ([]byte, error) {
	return btcec.Encrypt(pubKey, data)
}

// Decrypt decrypts data using a secp256k1 private key (ECIES)
func Decrypt(privKey *btcec.PrivateKey, data []byte) ([]byte, error) {
	return btcec.Decrypt(privKey, data)
}
```

The encryption method used here internally generates a new key every time. Therefore, even if the input is the same, the output is always different.

So you should refer to this code.
https://github.com/medibloc/doracle-poc/blob/with-panacea/pkg/secp256k1/encrypt.go#L14

example)
https://github.com/medibloc/doracle-poc/blob/with-panacea/pkg/secp256k1/encrypt_test.go#L37

### PR DESCRIPTION
**Pull request by inchori**
- To resolve [#52](https://github.com/medibloc/panacea-doracle/issues/52), change encrypt/decrypt method to AES256 when vote or join to oracle.
- I mark as TODO for add nonce in encrypt oraclePrivKey with shareKey when make `oracleRegistrationVote`.

### CODE REVIEW

File: event/register_oracle_event.go [hunk 1]
```diff
@@ -92,12 +93,11 @@ func verifyReportAndGetVoteOption(oracleRegistration *types.OracleRegistration,
 
 // makeOracleRegistrationVote makes a vote for oracle registration with VOTE_OPTION
 func makeOracleRegistrationVote(uniqueID, voterAddr, votingTargetAddr string, voteOption types.VoteOption, oraclePrivKey []byte, nodePubKey []byte) (*types.MsgVoteOracleRegistration, error) {
-	pubKey, err := btcec.ParsePubKey(nodePubKey, btcec.S256())
-	if err != nil {
-		return nil, err
-	}
+	privKey, pubKey := crypto.PrivKeyFromBytes(oraclePrivKey)
+	shareKey := crypto.ShareKey(privKey, pubKey)
```
Comment (0xHansLee) [inline event/register_oracle_event.go]: `nodePubKey` should be used for shareKey, not oracle public key :)

File: cmd/doracled/cmd/get_oracle_key.go [hunk 2]
```diff
@@ -100,8 +101,20 @@ func getOraclePrivKey(conf *config.Config, oracleRegistration *oracletypes.Oracl
...
+		oraclePubKeyPath := conf.AbsOraclePubKeyPath()
+		unsealOraclePubKey, err := sgx.UnsealFromFile(oraclePubKeyPath)
+		if err != nil {
+			return fmt.Errorf("failed to unseal from file: %w", err)
+		}
+
+		oraclePubKey, err := btcec.ParsePubKey(unsealOraclePubKey, btcec.S256())
+		if err != nil {
+			return fmt.Errorf("failed to parse oraclePubKey: %w", err)
+		}
```
Comment (0xHansLee) [inline cmd/doracled/cmd/get_oracle_key.go]: As you can probably see the `conf.AbsOraclePubKeyPath()`, the oracle pubkey file(default name of `oracle_pub_key.json`) is used to store oracle public key and its remote report in `gen-oracle-key` cmd.

In general, the oracle to register probably don't have the file, thus how about to get the oracle public key from Panacea using query client?

**Comment by gyuguen** [comment]
Please add test code.
As I expected, encryption/decryption in the test code will fail.

File: cmd/doracled/cmd/get_oracle_key.go (hunk 2 above)
Comment (inchori) [reply cmd/doracled/cmd/get_oracle_key.go]: Ah yes, I understand. The `oracle_pub_key.json` will be generated when using `gen-oracle-key` cmd. So I think you're right. I'll change it.

Comment (inchori) [reply cmd/doracled/cmd/get_oracle_key.go]: Fixed in [bd2279e](https://github.com/medibloc/panacea-doracle/pull/54/commits/bd2279e57d2a4307de9ce396325a2a35d9d43e16).

File: cmd/doracled/cmd/get_oracle_key.go [hunk 3]
```diff
@@ -78,7 +81,14 @@ func getOracleKeyCmd() *cobra.Command {
 				return errors.New("the existing node key is different from the one used in oracle registration. if you want to re-request RegisterOracle, delete the existing node_priv_key.sealed file and rerun register-oracle cmd")
 			}
 
-			return getOraclePrivKey(conf, oracleRegistration, nodePrivKey)
+			// TODO: This will be changed to the nonce that is field of oracleRegistration
```
Comment (gyuguen) [inline cmd/doracled/cmd/get_oracle_key.go]: This change is reflected in panacea-core. (https://github.com/medibloc/panacea-core/pull/404)
Modify it using the master branch of panacea-core.

Comment (inchori) [reply cmd/doracled/cmd/get_oracle_key.go]: BTW, I think we need to add `Nonce` field in `NewMsgRegisterOracle` in [x/oracle/type/message_oracle.go](https://github.com/medibloc/panacea-core/blob/2c0f80b0f08e2ba3db98593ddeb384931618dae2/x/oracle/types/message_oracle.go#L10).

File: cmd/doracled/cmd/get_oracle_key.go [hunk 4]
```diff
@@ -88,7 +98,7 @@ func getOracleKeyCmd() *cobra.Command {
 }
 
 // getOraclePrivKey handles OracleRegistration differently depending on the status of oracle registration
-func getOraclePrivKey(conf *config.Config, oracleRegistration *oracletypes.OracleRegistration, nodePrivKey *btcec.PrivateKey) error {
+func getOraclePrivKey(conf *config.Config, oracleRegistration *oracletypes.OracleRegistration, nodePrivKey *btcec.PrivateKey, nonce []byte, queryClient *panacea.QueryClient) error {
```
Comment (0xHansLee) [inline cmd/doracled/cmd/get_oracle_key.go]: The nonce would be included in `oracleRegistration` as you can see [here](https://github.com/medibloc/panacea-core/blob/2c0f80b0f08e2ba3db98593ddeb384931618dae2/proto/panacea/oracle/v2alpha2/oracle.proto#L71)

File: cmd/doracled/cmd/get_oracle_key.go (hunk 3 above)
Comment (gyuguen) [reply cmd/doracled/cmd/get_oracle_key.go]: Yes, I created this PR.(https://github.com/medibloc/panacea-core/pull/405)

File: crypto/encrypt.go [hunk 5]
```diff
@@ -11,3 +17,50 @@ func Encrypt(pubKey *btcec.PublicKey, data []byte) ([]byte, error) {
 func Decrypt(privKey *btcec.PrivateKey, data []byte) ([]byte, error) {
 	return btcec.Decrypt(privKey, data)
 }
+
+func EncryptWithAES256(key, nonce, data []byte) ([]byte, error) {
```
Comment (0xHansLee) [inline crypto/encrypt.go]:
```suggestion
func EncryptWithAES256(secretKey, nonce, data []byte) ([]byte, error) {
```
I suggested to rename the `key` to `secretKey`.

File: cmd/doracled/cmd/get_oracle_key.go [hunk 6]
```diff
@@ -100,10 +110,25 @@ func getOraclePrivKey(conf *config.Config, oracleRegistration *oracletypes.Oracl
 			return errors.New("the oracle private key already exists")
 		}
 
-		// else, get encryptedOraclePrivKey from Panacea and decrypt and SealToFile it
-		oraclePrivKey, err := crypto.Decrypt(nodePrivKey, oracleRegistration.EncryptedOraclePrivKey)
+		oraclePublicKey, err := queryClient.GetOracleParamsPublicKey()
```
Comment (0xHansLee) [inline cmd/doracled/cmd/get_oracle_key.go]: I think it would be better to get the `oraclePubKey` outside this function.

File: event/register_oracle_event.go [hunk 7]
```diff
@@ -102,12 +103,16 @@ func verifyReportAndGetVoteOption(oracleRegistration *types.OracleRegistration,
...
+
 	pubKey, err := btcec.ParsePubKey(nodePubKey, btcec.S256())
 	if err != nil {
 		return nil, err
 	}
 
-	encryptedOraclePrivKey, err := crypto.Encrypt(pubKey, oraclePrivKey)
+	shareKey := crypto.ShareKey(privKey, pubKey)
+	// TODO: Nonce will be added.
+	encryptedOraclePrivKey, err := crypto.EncryptWithAES256(shareKey, nil, oraclePrivKey)
```
Comment (0xHansLee) [inline event/register_oracle_event.go]: The nonce may be in the `oracleRegistration` obtained using query client in line 57. I think you can add it now :)

File: panacea/query_client.go [hunk 8]
```diff
@@ -316,3 +318,12 @@ func (q QueryClient) GetOracleRegistration(oracleAddr, uniqueID string) (*oracle
 func (q QueryClient) GetLightBlock(height int64) (*tmtypes.LightBlock, error) {
 	return q.lightClient.TrustedLightBlock(height)
 }
+
+func (q QueryClient) GetOracleParamsPublicKey() ([]byte, error) {
```
Comment (0xHansLee) [inline panacea/query_client.go]: Why don't we return the parsed oracle public key instead of byte array?
But it's not important for now. I just wonder your thoughts.

File: crypto/encrypt.go (hunk 5 above)
Comment (inchori) [reply crypto/encrypt.go]: Ah yes, I agree

File: panacea/query_client.go (hunk 8 above)
Comment (inchori) [reply panacea/query_client.go]: It doesn't have a big reason. But I think that put the parsing the byte of oracle public key to this function would be more better. So I can remove error handling for parsing public key in `get_oracle_key.go`.

Comment (inchori) [reply panacea/query_client.go]: Fixed in [a0fe48a](https://github.com/medibloc/panacea-doracle/pull/54/commits/a0fe48a929c83780c86a7930b28e5a5e62dc6885).

File: panacea/query_client.go [hunk 9]
```diff
@@ -319,11 +320,19 @@ func (q QueryClient) GetLightBlock(height int64) (*tmtypes.LightBlock, error) {
 	return q.lightClient.TrustedLightBlock(height)
 }
 
-func (q QueryClient) GetOracleParamsPublicKey() ([]byte, error) {
+func (q QueryClient) GetOracleParamsPublicKey() (*btcec.PublicKey, error) {
 	oraclePubKeyBz, err := q.GetStoreData(context.Background(), paramstypes.StoreKey, append(append([]byte(oracletypes.StoreKey), '/'), oracletypes.KeyOraclePublicKey...))
 	if err != nil {
 		return nil, err
 	}
+	if oraclePubKeyBz == nil {
```
Comment (inchori) [inline panacea/query_client.go:328]: For now, I just put an error handling for nil value of oracle public key when querying oracle params in panacea-core.

File: panacea/query_client.go [hunk 10]
```diff
@@ -316,3 +319,20 @@ func (q QueryClient) GetOracleRegistration(oracleAddr, uniqueID string) (*oracle
...
 }
+
+func (q QueryClient) GetOracleParamsPublicKey() (*btcec.PublicKey, error) {
+	oraclePubKeyBz, err := q.GetStoreData(context.Background(), paramstypes.StoreKey, append(append([]byte(oracletypes.StoreKey), '/'), oracletypes.KeyOraclePublicKey...))
+	if err != nil {
+		return nil, err
+	}
+	if oraclePubKeyBz == nil {
+		return nil, errors.New("the oracle public key's value is nil")
+	}
```
Comment (inchori) [inline panacea/query_client.go:330]: For now, I just put an error handling for nil value of oracle public key when querying oracle params in panacea-core.

**Review by gyuguen — APPROVED** [review]
LGTM 👍

**Review by 0xHansLee — APPROVED** [review]

File: crypto/key.go [hunk 11]
```diff
@@ -27,3 +28,7 @@ func GeneratePrivateKeyFromMnemonic(mnemonic string, coinType, accNum, index uin
 
 	return hd.DerivePrivateKeyForPath(master, ch, hdPath)
 }
+
+func ShareKey(priv *btcec.PrivateKey, pub *btcec.PublicKey) []byte {
```
Comment (youngjoon-lee) [inline crypto/key.go]:
```suggestion
func SharedKey(priv *btcec.PrivateKey, pub *btcec.PublicKey) []byte {
```

**Review by youngjoon-lee — APPROVED** [review]
